apiVersion: v1
kind: ConfigMap
metadata:
  name: eh-config-map
  namespace: kafka-eh-perf
data:
  BOOTSTRAP_SERVER: sofio-ce-eh.servicebus.windows.net:9093
  TOPIC_NAME: cibc-test
  NUM_PRODUCER_THREADS: "10"
  MESSAGE_SIZE_IN_BYTES: "512"
  TARGET_RECORDS_PER_SECOND: "1000"
  NUM_CONSUMER_GROUP_THREADS: "1"
  NUM_RECORDS_TO_READ_BEFORE_COMMIT: "0"
  SHOULD_START_FROM_END: "true"
  CONSUMER_GROUP_1: cg1
  CONSUMER_GROUP_2: cg2
  CONSUMER_GROUP_3: cg3
  CONSUMER_GROUP_4: cg4
  CONSUMER_GROUP_5: cg5
  CONSUMER_GROUP_6: cg6
  CONSUMER_GROUP_7: cg7
  CONSUMER_GROUP_8: cg8
  CONSUMER_GROUP_9: cg9
  CONSUMER_GROUP_10: cg10
  CONSUMER_GROUP_11: cg11
  CONSUMER_GROUP_12: cg12
  CONSUMER_GROUP_13: cg13
  CONSUMER_GROUP_14: cg14
  CONSUMER_GROUP_15: cg15
  CONSUMER_GROUP_16: cg16
  CONSUMER_GROUP_17: cg17
  CONSUMER_GROUP_18: cg18
  CONSUMER_GROUP_19: cg19
  CONSUMER_GROUP_20: cg20
  CONSUMER_GROUP_21: cg21
  CONSUMER_GROUP_22: cg22
  CONSUMER_GROUP_23: cg23
  CONSUMER_GROUP_24: cg24
  CONSUMER_GROUP_25: cg25
  CONSUMER_GROUP_26: cg26
  CONSUMER_GROUP_27: cg27
  CONSUMER_GROUP_28: cg28
  CONSUMER_GROUP_29: cg29
  CONSUMER_GROUP_30: cg30