#!/usr/bin/env bash
kubectl apply -f deployment1.yaml
kubectl apply -f deployment2.yaml
kubectl apply -f deployment3.yaml
kubectl apply -f deployment4.yaml
kubectl apply -f deployment5.yaml
kubectl apply -f deployment6.yaml
kubectl apply -f deployment7.yaml
kubectl apply -f deployment8.yaml
kubectl apply -f deployment9.yaml
kubectl apply -f deployment10.yaml
kubectl apply -f deployment11.yaml
kubectl apply -f deployment12.yaml
kubectl apply -f deployment13.yaml
kubectl apply -f deployment14.yaml
kubectl apply -f deployment15.yaml
kubectl apply -f deployment16.yaml
kubectl apply -f deployment17.yaml
kubectl apply -f deployment18.yaml
kubectl apply -f deployment19.yaml
kubectl apply -f deployment20.yaml
kubectl apply -f deployment21.yaml
kubectl apply -f deployment22.yaml
kubectl apply -f deployment23.yaml
kubectl apply -f deployment24.yaml
kubectl apply -f deployment25.yaml
kubectl apply -f deployment26.yaml
kubectl apply -f deployment27.yaml
kubectl apply -f deployment28.yaml
kubectl apply -f deployment29.yaml
kubectl apply -f deployment30.yaml