#!/usr/bin/env bash
kubectl delete deployment testconsumer1 -n kafka-eh-perf
kubectl delete deployment testconsumer2 -n kafka-eh-perf
kubectl delete deployment testconsumer3 -n kafka-eh-perf
kubectl delete deployment testconsumer4 -n kafka-eh-perf
kubectl delete deployment testconsumer5 -n kafka-eh-perf
kubectl delete deployment testconsumer6 -n kafka-eh-perf
kubectl delete deployment testconsumer7 -n kafka-eh-perf
kubectl delete deployment testconsumer8 -n kafka-eh-perf
kubectl delete deployment testconsumer9 -n kafka-eh-perf
kubectl delete deployment testconsumer10 -n kafka-eh-perf
kubectl delete deployment testconsumer11 -n kafka-eh-perf
kubectl delete deployment testconsumer12 -n kafka-eh-perf
kubectl delete deployment testconsumer13 -n kafka-eh-perf
kubectl delete deployment testconsumer14 -n kafka-eh-perf
kubectl delete deployment testconsumer15 -n kafka-eh-perf
kubectl delete deployment testconsumer16 -n kafka-eh-perf
kubectl delete deployment testconsumer17 -n kafka-eh-perf
kubectl delete deployment testconsumer18 -n kafka-eh-perf
kubectl delete deployment testconsumer19 -n kafka-eh-perf
kubectl delete deployment testconsumer20 -n kafka-eh-perf
kubectl delete deployment testconsumer21 -n kafka-eh-perf
kubectl delete deployment testconsumer22 -n kafka-eh-perf
kubectl delete deployment testconsumer23 -n kafka-eh-perf
kubectl delete deployment testconsumer24 -n kafka-eh-perf
kubectl delete deployment testconsumer25 -n kafka-eh-perf
kubectl delete deployment testconsumer26 -n kafka-eh-perf
kubectl delete deployment testconsumer27 -n kafka-eh-perf
kubectl delete deployment testconsumer28 -n kafka-eh-perf
kubectl delete deployment testconsumer29 -n kafka-eh-perf
kubectl delete deployment testconsumer30 -n kafka-eh-perf