apiVersion: apps/v1
kind: Deployment
metadata:
  name:  testconsumer18
  namespace: kafka-eh-perf
  labels:
    app:  testconsumer18
spec:
  selector:
    matchLabels:
      app: testconsumer18
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  testconsumer18
    spec:
      containers:
      - name:  testconsumer18
        image:  sofioehtestacr.azurecr.io/azure-eh-kafka-test-consumer:latest
        resources:
          limits:
            cpu: 250m
            memory: 500Mi
        env:
        - name: BOOTSTRAP_SERVER
          valueFrom:
            configMapKeyRef:
              name: eh-config-map
              key: BOOTSTRAP_SERVER
        - name: TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: eh-config-map
              key: TOPIC_NAME
        - name: CONSUMER_GROUP_NAME
          valueFrom:
            configMapKeyRef:
              name: eh-config-map
              key: CONSUMER_GROUP_18
        - name: SASL_JAAS_CONFIG
          valueFrom:
            secretKeyRef:
              name: eh-secrets
              key: SASL_JAAS_CONFIG
      restartPolicy: Always