apiVersion: apps/v1
kind: Deployment
metadata:
  name:  TestConsumer1
  namespace: kafka-eh-perf
  labels:
    app:  TestConsumer1
spec:
  selector:
    matchLabels:
      app: TestConsumer1
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  TestConsumer1
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  TestConsumer1
        image:  MYAPP:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        - name: BOOTSTRAP_SERVER
          valueFrom:
            configMapKeyRef:
              name: eh-config
              key: BOOTSTRAP_SERVER
        - name: CONSUMER_GROUP_NAME
          valueFrom:
            configMapKeyRef:
              name: eh-config
              key: CONSUMER_GROUP_NAME
        - name: TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: eh-config
              key: TOPIC_NAME
        ports:
        - containerPort:  80
          name:  TestConsumer1
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      restartPolicy: Always